setup:
	python3 -m venv ~/.MSDS_434

install:
	pip install --upgrade pip &&\
		pip install -r requirements.txt

test:
	python -m pytest -vv --cov=MSDS_434 tests/*.py
	python -m pytest --nbval notebook.ipynb


lint:
	pylint --disable=R,C MSDS_434 cli web

all: install lint test